apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  selector: 
    app: flask-app
  type: NodePort      #Using only as I am sharing the service api
  ports:
    - port: 5000
      targetPort: 5000
